before_script:
      - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
      - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser

script:
    - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -v colors
