local Color = require("colorbuddy.color").Color

Color:new("white", "#F5F5F0")
Color:new("white_darker", "#D0D0D0")
Color:new("black", "#323232")
Color:new("lightblack", "#3A3A35")
Color:new("very_pale_yellow", "#ffffdd")
Color:new("darkblack", "#282826")
Color:new("grey", "#A8A8A0")
Color:new("lightgrey", "#707080")
Color:new("darkgrey", "#4A4A4A")
Color:new("warmgrey", "#B09070")

Color:new("pink", "#FF69B4") -- brighter pink
Color:new("green", "#A0E000") -- lighter strong green
Color:new("springgreen", "#20FFA0")
Color:new("aqua", "#80E5FF")
Color:new("yellow", "#F0E890")
Color:new("orange", "#FFB040")
Color:new("lightorange", "#FFB070")
Color:new("tomato", "#FF8070")
Color:new("purple", "#F0A0F0")
Color:new("chartreuse", "#A0FF40")
Color:new("red", "#FF5070")
Color:new("blue", "#40D0FF") -- lighter deep sky blue
Color:new("vivid_blue", "#50A8FF")
Color:new("light_blue", "#60D8FF")
Color:new("darkred", "#8F0000")
Color:new("darkturquoise", "#40E8E8")
Color:new("coral", "#FF9870")
Color:new("softred", "#FF9888")
Color:new("vivid_yellow", "#FFE040")
Color:new("light_yellow", "#FFFF88")
Color:new("very_light_orange", "#FFE0A0")
Color:new("very_soft_orange", "#FFE0B8")
Color:new("vivid_orange", "#FFD850")
Color:new("lime_green", "#B8FFD0")
Color:new("light_green", "#D8FF88")
Color:new("camel", "#D8B088")
Color:new("crimson", "#FF3050")
Color:new("very_soft_yellow", "#FFF0D0")
Color:new("very_soft_red", "#FFD0D8")
Color:new("pure_pink", "#FF40A0")
Color:new("pale_orange", "#FFE8D0")
Color:new("tea_green", "#E0FFD8")

Color:new("addfg", "#D7FFAF")
Color:new("addbg", "#5F875F")
Color:new("delbg", "#F75F5F")
Color:new("changefg", "#D7D7FF")
Color:new("changebg", "#5F5F87")
