local Color = require("colorbuddy.color").Color

Color:new("white", "#E8E8E3")
Color:new("white_darker", "#b8b8b8")
Color:new("black", "#323232")
Color:new("lightblack", "#2D2E27")
Color:new("very_pale_yellow", "#ffffcc")
Color:new("darkblack", "#211F1C")
Color:new("grey", "#8F908A")
Color:new("lightgrey", "#575B61")
Color:new("darkgrey", "#3C3C3C")
Color:new("warmgrey", "#907D57")

Color:new("pink", "#F92772") -- bright pink
Color:new("green", "#8AD000") -- strong green
Color:new("springgreen", "#00FF7F")
Color:new("aqua", "#66D9EF")
Color:new("yellow", "#E6DB74")
Color:new("orange", "#FD9720")
Color:new("lightorange", "#FF8247")
Color:new("tomato", "#FF6347")
Color:new("purple", "#EE82EE")
Color:new("chartreuse", "#7FFF00")
Color:new("red", "#E73C50")
Color:new("blue", "#00BFFF") -- deep sky blue
Color:new("vivid_blue", "#198CFF")
Color:new("light_blue", "#00BFFF")
Color:new("darkred", "#5F0000")
Color:new("darkturquoise", "#00CED1")
Color:new("coral", "#FF7F50")
Color:new("softred", "#EF7C66")
Color:new("vivid_yellow", "#FFD517")
Color:new("light_yellow", "#FFFF66")
Color:new("very_light_orange", "#FFD280")
Color:new("very_soft_orange", "#fecf9e")
Color:new("vivid_orange", "#ffc833")
Color:new("lime_green", "#9FFFC2")
Color:new("camel", "#C19A6B")
Color:new("crimson", "#DC143C")
Color:new("very_soft_yellow", "#f0e2b5")
Color:new("very_soft_red", "#F0B5C3")
Color:new("pure_pink", "#ff0080")
Color:new("pale_orange", "#ffd9b2")
Color:new("tea_green", "#d0f0c0")

Color:new("addfg", "#D7FFAF")
Color:new("addbg", "#5F875F")
Color:new("delbg", "#F75F5F")
Color:new("changefg", "#D7D7FF")
Color:new("changebg", "#5F5F87")
